export async function fetchApplicants() {
  return [
    {
      projectName: "Sistema de automatización",
      applicants: [
        {
          employeeId: "EMP001",
          name: "Sofía Schneider",
          email: "sofia@accenture.com",
          role: "Front-end Developer",
          level: "10",
          cargability: 30,
          applicationDate: "19/05/2025",
          interests: 3,
          skills: 8,
        },
        {
          employeeId: "EMP002",
          name: "Mauricio Lozano",
          email: "mauricio@accenture.com",
          role: "Backend Developer",
          level: "9",
          cargability: 40,
          applicationDate: "25/04/2025",
          interests: 2,
          skills: 5,
        },
        {
          employeeId: "EMP003",
          name: "Katia Martín del Campo",
          email: "katia@accenture.com",
          role: "Full-stack Developer",
          level: "11",
          cargability: 50,
          applicationDate: "31/03/2025",
          interests: 5,
          skills: 10,
        },
        {
          employeeId: "EMP004",
          name: "Sergio Vargas",
          email: "sergio@accenture.com",
          role: "Data Engineer",
          level: "8",
          cargability: 35,
          applicationDate: "19/05/2025",
          interests: 3,
          skills: 8,
        },
        {
          employeeId: "EMP006",
          name: "Hervey Navarro",
          email: "hervey@accenture.com",
          role: "DevOps Engineer",
          level: "10",
          cargability: 45,
          applicationDate: "25/04/2025",
          interests: 2,
          skills: 5,
        },
        {
          employeeId: "EMP007",
          name: "Nicolás Treviño",
          email: "nicolas@accenture.com",
          role: "Mobile Developer",
          level: "9",
          cargability: 20,
          applicationDate: "31/03/2025",
          interests: 5,
          skills: 10,
        },
      ],
    },
    {
      projectName: "Dashboard de métricas financieras",
      applicants: [
        {
          employeeId: "EMP004",
          name: "Luis Alberto Fernández",
          email: "luis@accenture.com",
          role: "Data Analyst",
          level: "10",
          cargability: 60,
          applicationDate: "15/05/2025",
          interests: 4,
          skills: 6,
        },
        {
          employeeId: "EMP005",
          name: "Daniela Ruiz Navarro",
          email: "daniela@accenture.com",
          role: "UX Designer",
          level: "9",
          cargability: 70,
          applicationDate: "10/05/2025",
          interests: 3,
          skills: 7,
        },
      ],
    },
    {
      projectName: "Chatbot de atención al cliente",
      applicants: [
        {
          employeeId: "EMP006",
          name: "Carlos Mendoza Pérez",
          email: "carlos@accenture.com",
          role: "AI Engineer",
          level: "11",
          cargability: 25,
          applicationDate: "22/04/2025",
          interests: 5,
          skills: 9,
        },
        {
          employeeId: "EMP007",
          name: "Isabel Torres Sánchez",
          email: "isabel@accenture.com",
          role: "QA Engineer",
          level: "8",
          cargability: 55,
          applicationDate: "20/04/2025",
          interests: 4,
          skills: 8,
        },
      ],
    },
    {
      projectName: "Plataforma de seguimiento de objetivos",
      applicants: [
        {
          employeeId: "EMP008",
          name: "Miguel Ángel Herrera",
          email: "miguel@accenture.com",
          role: "Business Analyst",
          level: "9",
          cargability: 50,
          applicationDate: "12/05/2025",
          interests: 3,
          skills: 7,
        },
        {
          employeeId: "EMP009",
          name: "Fernanda Gómez Rivas",
          email: "fernanda@accenture.com",
          role: "Project Manager",
          level: "12",
          cargability: 30,
          applicationDate: "11/05/2025",
          interests: 5,
          skills: 9,
        },
      ],
    },
  ];
}


export async function fetchFeedback() {
  return [
    {
      feedbackId: "FB001",
      employeeId: "EMP001",
      projectManager: "Luis Martínez",
      comment: "Excelente colaboración y proactividad en todo momento.",
      date: "10/04/2025",
    },
    {
      feedbackId: "FB008",
      employeeId: "EMP001",
      projectManager: "Ana Gómez",
      comment: "Muy atenta a los detalles, siempre entrega a tiempo.",
      date: "12/04/2025",
    },
    {
      feedbackId: "FB009",
      employeeId: "EMP001",
      projectManager: "Carlos Jiménez",
      comment: "Demostró liderazgo al resolver situaciones críticas.",
      date: "14/04/2025",
    },
    {
      feedbackId: "FB010",
      employeeId: "EMP001",
      projectManager: "Laura Torres",
      comment: "Actitud positiva y excelente comunicación.",
      date: "16/04/2025",
    },
    {
      feedbackId: "FB011",
      employeeId: "EMP001",
      projectManager: "Gabriela Soto",
      comment: "Buen dominio técnico y facilidad para aprender rápido.",
      date: "18/04/2025",
    },
    {
      feedbackId: "FB012",
      employeeId: "EMP001",
      projectManager: "Andrés Salgado",
      comment: "Siempre dispuesta a colaborar y ayudar al equipo.",
      date: "20/04/2025",
    },
    {
      feedbackId: "FB013",
      employeeId: "EMP001",
      projectManager: "Santiago Rivas",
      comment: "Consistentemente supera las expectativas.",
      date: "22/04/2025",
    },
    {
      feedbackId: "FB014",
      employeeId: "EMP001",
      projectManager: "Elena Rodríguez",
      comment: "Excelente actitud frente a nuevos desafíos.",
      date: "24/04/2025",
    },
    {
      feedbackId: "FB015",
      employeeId: "EMP001",
      projectManager: "Ricardo Morales",
      comment: "Aporta ideas valiosas y ejecuta con precisión.",
      date: "26/04/2025",
    },
    {
      feedbackId: "FB016",
      employeeId: "EMP001",
      projectManager: "Patricia Vega",
      comment: "Tiene una gran capacidad de organización y seguimiento.",
      date: "28/04/2025",
    },

    {
      feedbackId: "FB003",
      employeeId: "EMP003",
      projectManager: "Carlos Jiménez",
      comment: "Muy resolutiva y con gran dominio del stack asignado.",
      date: "18/04/2025",
    },
    {
      feedbackId: "FB004",
      employeeId: "EMP004",
      projectManager: "Laura Torres",
      comment: "Buen desempeño general, aunque podría ser más puntual con entregas.",
      date: "15/02/2025",
    },
    {
      feedbackId: "FB005",
      employeeId: "EMP006",
      projectManager: "Gabriela Soto",
      comment: "Gran conocimiento en infraestructura, excelente en tiempos de crisis.",
      date: "20/03/2025",
    },
    {
      feedbackId: "FB006",
      employeeId: "EMP007",
      projectManager: "Andrés Salgado",
      comment: "Muy creativo y con gran disposición para aprender.",
      date: "22/03/2025",
    },
    {
      feedbackId: "FB007",
      employeeId: "EMP009",
      projectManager: "Santiago Rivas",
      comment: "Liderazgo claro y habilidades organizativas destacables.",
      date: "05/04/2025",
    },
  ];
}
